#!/bin/bash
#
# Script to set up OpenVPN for routing all traffic.
# derived from https://github.com/tinfoil/openvpn_autoconfig
#
set -e

if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user" 1>&2
  exit 1
fi

KEY_SIZE="4096"
SERVER_NAME="ShyVPN"
SERVER_ADDRESS=$(curl -s4 https://canhazip.com || echo "<insert server IP here>")

apt-get update -q
debconf-set-selections <<EOF
iptables-persistent iptables-persistent/autosave_v4 boolean true
iptables-persistent iptables-persistent/autosave_v6 boolean true
EOF
apt-get install -qy openvpn curl iptables-persistent

cd /etc/openvpn

# This can take a long time; background it while we setup everything else
# Diffie hellman parameters
>dh.pem     openssl dhparam $KEY_SIZE &

# Certificate Authority
>ca-key.pem      openssl genrsa $KEY_SIZE
>ca-csr.pem      openssl req -new -key ca-key.pem -subj /CN=$SERVER_NAME-CA/
>ca-cert.pem     openssl x509 -req -in ca-csr.pem -signkey ca-key.pem -days 365
>ca-cert.srl     echo 01

# Server Key & Certificate
>server-key.pem  openssl genrsa $KEY_SIZE
>server-csr.pem  openssl req -new -key server-key.pem -subj /CN=$SERVER_NAME-Server/
>server-cert.pem openssl x509 -req -in server-csr.pem -CA ca-cert.pem -CAkey ca-key.pem -days 365

chmod 600 *-key.pem

# Set up IP forwarding and NAT for iptables
>>/etc/sysctl.conf echo net.ipv4.ip_forward=1
sysctl -p /etc/sysctl.conf

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
>/etc/iptables/rules.v4 iptables-save

# Write configuration files for client and server

>tcp443.conf cat <<EOF
server      10.8.0.0 255.255.255.0
verb        3
duplicate-cn
key         server-key.pem
ca          ca-cert.pem
cert        server-cert.pem
dh          dh.pem
keepalive   10 120
persist-key yes
persist-tun yes
comp-lzo    yes
push        "dhcp-option DNS 8.8.8.8"
push        "dhcp-option DNS 8.8.4.4"

# Normally, the following command is sufficient.
# However, it doesn't assign a gateway when using
# VMware guest-only networking.
#
# push        "redirect-gateway def1 bypass-dhcp"

push        "redirect-gateway bypass-dhcp"
push        "route-metric 512"
push        "route 0.0.0.0 0.0.0.0"

user        nobody
group       nogroup

proto       tcp
port        443
dev         tun443
status      openvpn-status-443.log
EOF

service openvpn restart

## script to generate clients
>/root/add_client cat << 'EOSCRIPT'
CLIENT=$1
KEY_SIZE=$2
SERVER_IP=$3
: ${SERVER_IP:=$(curl -s4 https://canhazip.com)}

mkdir -p "/etc/openvpn/clients/$CLIENT"
pushd "/etc/openvpn/clients/$CLIENT" > /dev/null
# Client Key & Certificate
>client-key.pem  openssl genrsa $KEY_SIZE
>client-csr.pem  openssl req -new -key client-key.pem -subj /CN=$CLIENT/
>client-cert.pem openssl x509 -req -in client-csr.pem -CA /etc/openvpn/ca-cert.pem -CAkey /etc/openvpn/ca-key.pem -days 365

>client.ovpn cat << EOF
client
nobind
dev tun
redirect-gateway def1 bypass-dhcp
remote $SERVER_IP 443 tcp
comp-lzo yes

<key>
$(cat client-key.pem)
</key>
<cert>
$(cat client-cert.pem)
</cert>
<ca>
$(cat /etc/openvpn/ca-cert.pem)
</ca>
EOF

echo "client configuration at /etc/openvpn/clients/$CLIENT/client.ovpn"
popd > /dev/null
EOSCRIPT

chmod 500 /root/add_client
/root/add_client client
cd -
